### ISSUE TITLE
403 from jcenter.bintray.com on auto-update

### ISSUE THREAD

**Issue by Adam-McDevitt** [andrea-vinci/Insulator#175]
**Describe the bug**
Cannot launch fresh insulator install as auto-update fails to download dependencies from JCenter.

**To Reproduce**
1. Install Insulator from `.deb` package
2. Launch Insulator

**Expected behavior**
Auto-update runs and downloads dependencies

**Screenshots**
![image](https://user-images.githubusercontent.com/23368702/111670660-fae30100-880f-11eb-9683-b33cded3f341.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04.2 LTS

**Additional context**
I assume this is related to the [JCenter/Bintray sunsetting](https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/).

**Comment by andrewinci** [comment]
The issue should be fixed by https://github.com/andrea-vinci/Insulator/releases/tag/0.3.7
Could you try to start the application and verify please?

**Comment by Adam-McDevitt** [comment]
Yep that worked. Thanks @andrewinci
